In [35]:
import tensorflow as tf


print(tf.__version__)

v = tf.Variable([1 ,3] , [3 , 5])
a = tf.constant(value= [[ 1 ,2 ] , [3  , 4]]) 
b = tf.constant(value= [[5 , 6] , [7 , 8]])



2.10.0


In [34]:
ab_concatenated= tf.concat(values=[a,b] , axis = 0 )
print(ab_concatenated)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)


In [33]:
ones = tf.ones(shape= [3 , 4])
ones_reshaped = tf.reshape(tensor= ones , shape= [4 , 3 ]) 
print(ones)
print(ones_reshaped)



tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [32]:

zeros = tf.zeros(shape= [ 3 , 4])
print(zeros)


tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [31]:
random = tf.random.normal(shape= [3 ,4])
random2 = tf.cast(random ,tf.int32 )
random3 = tf.transpose(random)
print(random)
print(random2)
print(random3)

tf.Tensor(
[[ 1.1794276  -0.19124176  0.6713962   0.3941233 ]
 [-2.2080843   0.14798874 -0.78069    -0.20578551]
 [ 2.3516834  -0.35085937  0.81409734  0.45681927]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ 1  0  0  0]
 [-2  0  0  0]
 [ 2  0  0  0]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 1.1794276  -2.2080843   2.3516834 ]
 [-0.19124176  0.14798874 -0.35085937]
 [ 0.6713962  -0.78069     0.81409734]
 [ 0.3941233  -0.20578551  0.45681927]], shape=(4, 3), dtype=float32)


In [30]:
mat1 = tf.constant([[3, 4 ,5 ] , [6 ,7 ,8] , [10 , 11 , 12]])
mat2 = tf.constant([[1], [2] , [9]])


print(tf.matmul(mat1 , mat2))
print(tf.multiply(mat1 , mat2))
row , column = mat1.shape
print(tf.eye(num_columns= column , num_rows= row , dtype= tf.int32))

tf.Tensor(
[[ 56]
 [ 92]
 [140]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[  3   4   5]
 [ 12  14  16]
 [ 90  99 108]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)
